### ISSUE TITLE
New NPM release 1.5

### ISSUE THREAD

**Issue by SebastianIoanPop** [ve-interactive/redis-statsd-reporter#8]
Hello @andyroyle ,

We have added a new type of monitor for zsets
Let us know if you agree with the change and if you do would it be possible to get a new npm release of this project?

Thanks!

**Comment by andyroyle** [comment]
is there an in-house npm account that i can give control of this module to? Or failing that your personal account?

**Comment by SebastianIoanPop** [comment]
As I am yet to receive a response with the company's NPM account I think it would be best to transfer it to my personal account and then I will transfer it later
https://www.npmjs.com/~spop

**Comment by devcfgc** [comment]
This is the npm account where that should be transferred https://www.npmjs.com/~itopsinfra @andyroyle thanks for your help

**Comment by andyroyle** [comment]
I've added itopsinfra and removed my personal account 👍
